baseURL = 'https://site.manuel-rhdt.de/'
languageCode = 'en-us'
title = 'Manuel Reinhardt'
copyright = "¬© Manuel Reinhardt 2026"
theme = 'minima'

# Allow raw HTML in Markdown
[markup.goldmark.renderer]
unsafe= true

[params.author]
name = "Manuel Reinhardt"
slogon = ""
description = "PhD in Physics specializing in computational modeling, Monte Carlo simulations, and information theory. Former researcher at [AMOLF](https://amolf.nl) Amsterdam in the Biochemical Networks group."

[params]
# iam is the beginning words of your self-introduction.
iam = "Hi, I'm"
# The subtitle will be shown after the title of your blog site.
# e.g. "title - subtitle".
subtitle = ""
# Comment decides the comment plugin to be used on your blog site, 
# e.g. disqus, utterances, ovo.
comment = ""
# Timeformat, no matter what format to use, make it the second day of Jan. 2006
timeformat = "2 Jan 2006"
# switch for turning on/off lights.
switch = ["üåô", "‚òÄÔ∏è"]
# default theme. e.g. light, dark, system
defaultTheme = "system"
# If set true, date of posts will be shown in the homepage.
displayDate = true
# If set true, users can select text from your post.
selectable = true
# Custom global font. notice: `globalFontFamily` won't be working
# on texts in some special positions like on titles
globalFontFamily = ""
# If set true, all your posts will use the chosen comment plugin
# except those with a `comment: false` in their front-matter
commentOnAllPosts = true
# toc decides the shape of the toc button. e.g. default, lines, bar
toc = "lines"

# Custom CSS
custom_css = ["/css/custom.css"]

[[menu.main]]
name = "Home"
url = "/"
weight = 1
[[menu.main]]
name = "Publications"
url = "/publication"
weight = 2
[[menu.main]]
name = "Presentations"
url = "/presentation"
weight = 3
[[menu.main]]
name = "Posters"
url = "/poster"
weight = 4
[[menu.main]]
name = "CV"
url = "/cv"
weight = 5


[[params.social]]
name = "github"  
url = "https://github.com/manuel-rhdt"
svg = ""

[taxonomies]
category = "categories"
